name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --configuration Release --no-restore

    - name: Publish application
      run: dotnet publish --configuration Release --output ./publish

    # - name: Install Swashbuckle CLI
    #   run: dotnet tool install Swashbuckle.AspNetCore.Cli

    - name: Install Swashbuckle CLI
      run: dotnet new tool-manifest && dotnet tool install Swashbuckle.AspNetCore.Cli

    - name: Generate OpenAPI Spec
      run: dotnet swagger tofile --output openapi.json ./publish/Test.dll v1

    # - name: Generate OpenApi Spec with Yaml
    #   run: dotnet swagger tofile --yaml --output openapi.yaml ./publish.Test.dll v1

    # - name: Setup Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 18

    # - name: Install Redocly CLI
    #   run: npm install @redocly/cli -g

    # - name: Push OpenAPI to Redocly
    #   run: redocly push my-api

     # Step 6: Upload the build output as an artifact
    - name: Upload Build Output
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: ./publish

      # Step 7: Upload the OpenAPI spec as an artifact
    - name: Upload OpenAPI Spec
      uses: actions/upload-artifact@v3
      with:
        name: openapi-spec
        path: openapi.json

    # - name: Upload OpenAPI Spec As Yaml
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: openapi-spec
    #     path: openapi.yaml

  push-to-redocly:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    needs: build
    environment: Dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: 'Push files and wait for deployment'
        uses: redocly/reunite-push-action@v1
        with:
          organization: 'test-p4cb6'
          project: 'testpr'
          mountPath: '/remote-repo-cicd'
          files: 'openapi.json'
          domain: 'https://app.cloud.redocly.com'
        env:
          REDOCLY_AUTHORIZATION: ${{ secrets.REDOCLY_AUTHORIZATION }}
