name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Dotnet Tool Restore
      run: dotnet tool restore

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --configuration Release --no-restore

    - name: Publish application
      run: dotnet publish --configuration Release --output ./publish

    - name: Install Swashbuckle CLI
      run: dotnet new tool-manifest && dotnet tool install Swashbuckle.AspNetCore.Cli

    - name: Generate OpenAPI Spec
      run: dotnet swagger tofile --output openapi.json ./publish/Test.dll v1
  
    - name: Upload Build Output
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: ./publish

    - name: Upload OpenAPI Spec
      uses: actions/upload-artifact@v3
      with:
        name: openapi-spec
        path: |
          openapi.json
          redocly.yaml

  push-to-redocly:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    needs: build
    environment: Dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download OpenAPI Spec Artifact
        uses: actions/download-artifact@v3
        with:
          name: openapi-spec
          path: ./downloaded-artifacts
      
      - name: 'Push files and wait for deployment'
        uses: redocly/reunite-push-action@v1
        with:
          organization: 'test-p4cb6'
          project: 'testpr'
          mountPath: '/remote-repo-cicd'
          files: './downloaded-artifacts/openapi.json ./downloaded-artifacts/redocly.yaml'
          domain: 'https://app.cloud.redocly.com'
        env:
          REDOCLY_AUTHORIZATION: ${{ secrets.REDOCLY_AUTHORIZATION }}
